# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: daily_updates

on:
  schedule:
    - cron: '0 3 * * 0' # JST 12:00
  push:

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 180
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set git information
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"   
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY 
    - name: Data Preprocess
      run: |
        python ./data/data_preprocess.py
    - name: Generate and add Gaussian figures
      run: |
        python ./data/gaussian_generator.py
        git add ./data/gaussian_figs_short/
        git add ./data/gaussian_figs_long/
        git add ./data/gaussian_alarm_results.csv
    - name: Generate and add exponential figures
      run: |
        python ./data//exponential_generator.py
        git add ./data/exponential_figs_short/
        git add ./data/exponential_figs_long/
        git add ./data/exponential_alarm_results.csv
    - name: Post to slack
      run:
        python ./data/post_slack.py daily_updates
    - name: Commit and push files
      run: |
        git commit --allow-empty -m "daily updates"
        git push